name: jupyter-book-env

channels:
  - conda-forge

dependencies:
  - numpy
  - matplotlib
  - scipy
  - pip
  - jupyterlite-sphinx
  - jupyterquiz
  - jupyter-book
  - pip:
    - jupyterlite-xeus-python