name: deploy

on:
  pull_request:
    branches:
      - publish
    types:
      - closed
    paths:
      - "book/**"
      - ".github/workflows/**"

defaults:
  run:
    shell: bash

jobs:
  release-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: '1.4.2'
          environment-file: 'environment.yml'

      - name: Build book
        shell: bash -el {0}
        run: |
          jupyter-book build book/

      - name: GitHub Pages actions
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: book/_build/html/